name: jaspr_provider
description: A wrapper around InheritedComponent to make them easier to use and more reusable.
version: 0.0.3
repository: https://github.com/Maksimka101/jaspr_provider

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  jaspr: ^0.1.4

dev_dependencies:
  jaspr_test: ^0.1.0
  mockito: ^5.2.0
